FROM node:20-bullseye-slim

WORKDIR /app

COPY package.json package-lock.json ./

# #Clean Install
# RUN npm cache clean --force
# RUN rm -rf node_modules package-lock.json
RUN npm ci --only=production=false


# Copy the rest of the source
COPY . .

EXPOSE 80

CMD ["npx", "npm", "run", "dev"]
