FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

# install nodemon globally (dev only)
RUN npm install -g nodemon

COPY . .

EXPOSE 4000

CMD ["npm", "run", "dev"]   # package.json should have: "dev": "nodemon index.js"
